version: '3'
services:
  db:
    image: postgres
    env_file: ./.env
  node:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    command: bash -c "bin/webpack-dev-server"
    env_file: ./.env
    volumes:
      - ./public:/myapp/public
    ports:
      - "8080:8080"
  rails:
    build:
      context: .
      dockerfile: Dockerfile.rails
    command: bash -c "sleep 3 && bundle exec rails db:setup && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: ./.env
    volumes:
      - ./public:/myapp/public
    ports:
      - "3000:3000"
    depends_on:
      - db
      - node
